USE COMPANY;
SELECT*FROM FACULTYMEMBERS;
SELECT*FROM courses;

WITH FACULTY_DEPT AS (
	SELECT concat(FIRST_NAME," ", LAST_NAME) AS FULL_NAME, DEPARTMENT
    FROM FACULTYMEMBERS
)
SELECT * FROM FACULTY_DEPT WHERE FULL_NAME LIKE "A%";