USE UNIVERSITY;
CREATE TABLE Event (
    Event_ID INT PRIMARY KEY AUTO_INCREMENT,
    Event_Name VARCHAR(100),
    Event_Date DATE,
    Event_Time TIME
);

INSERT INTO Event (Event_Name, Event_Date, Event_Time) VALUES
('Seminar', '2024-03-06', '15:00:00'),
('Conference', '2024-03-07', '10:30:00'),
('Workshop', '2024-03-08', '13:45:00'),
('Meeting', '2024-03-09', '09:30:00'),
('Presentation', '2024-03-10', '11:15:00'),
('Training', '2024-03-11', '14:00:00'),
('Seminar', '2024-03-12', '16:30:00'),
('Conference', '2024-03-13', '12:00:00'),
('Workshop', '2024-03-14', '15:45:00'),
('Meeting', '2024-03-15', '10:00:00'),
('Presentation', '2024-03-16', '14:30:00'),
('Training', '2024-03-17', '09:45:00'),
('Seminar', '2024-03-18', '17:00:00'),
('Conference', '2024-03-19', '11:30:00'),
('Workshop', '2024-03-20', '16:15:00');


SELECT DAY(EVENT_DATE) AS EVENT_DAY, EVENT_NAME FROM EVENT;
SELECT DATE(EVENT_DATE) AS EVENT_DATE, EVENT_NAME FROM EVENT;
SELECT TIME(EVENT_TIME) AS EVENT_DATE, EVENT_NAME FROM EVENT;
SELECT HOUR(EVENT_TIME) AS EVENT_TIME, EVENT_NAME FROM EVENT;
SELECT DATE(EVENT_DATE) AS EVENT_DATE, EVENT_NAME FROM EVENT;
SELECT DAYNAME(EVENT_DATE) AS EVENT_DAY ,EVENT_NAME FROM EVENT;
SELECT WEEKDAY(EVENT_DATE) AS WEEK_DAY ,EVENT_NAME FROM EVENT;
SELECT MONTHNAME(EVENT_DATE) AS EVENT_DAY ,EVENT_NAME FROM EVENT;
SELECT year(EVENT_DATE) AS EVENT_YEAR ,EVENT_NAME FROM EVENT;
SELECT MONTH(EVENT_DATE) AS EVENT_MONTH ,EVENT_NAME FROM EVENT;
SELECT WEEK(EVENT_DATE) AS EVENT_WEEK ,EVENT_NAME FROM EVENT;
SELECT LAST_DAY(EVENT_DATE) AS EVENT_MONTH ,EVENT_NAME FROM EVENT;
SELECT dayname(EVENT_DATE) AS EVENT_DAY ,EVENT_NAME FROM EVENT;
SELECT HOUR(EVENT_TIME) AS EVENT_HOUR ,EVENT_NAME FROM EVENT;
SELECT TIME(EVENT_TIME) AS EVENT_TIME ,EVENT_NAME FROM EVENT;
SELECT MINUTE(EVENT_TIME) AS EVENT_MINUITE ,EVENT_NAME FROM EVENT;
SELECT HOUR(NOW()) AS EVENT_TIME ,EVENT_NAME FROM EVENT;
SELECT minute(now());
SELECT date_add('EVENT_DATE', INTERVAL 5 DAY) AS NEW_EVENT_DAY FROM EVENT;
SELECT date_SUB('EVENT_DATE', INTERVAL 5 DAY) AS NEW_EVENT_DAY FROM EVENT;
SELECT dateDIFF('EVENT_DATE','EVENT_DATE') AS NEW_EVENT_DAY FROM EVENT;
SELECT now();
SELECT curdate();
SELECT current_time();
SELECT current_user();
SELECT hour(now());
SELECT minute(now());
SELECT second(now());
SELECT dayofmonth(now());
SELECT dayname(NOW());
COMMIT;