USE SIMPLELEARN;

SELECT*FROM employee1;

-- TO FIND DUPLICATE VALUES 
SELECT FIRST_NAME, LAST_NAME, COUNT(*) FROM EMPLOYEE1
GROUP BY FIRST_NAME, LAST_NAME HAVING COUNT(*) >1;

-- TO DELETE DUPLICATE VALUE  THRPUGH SUBQUERY 

DELETE FROM EMPLOYEE1 WHERE EMPLOYEE_ID NOT IN ( SELECT MAX(EMPLOYEE_ID) FROM EMPLOYEE 
GROUP BY FIRST_NAME, LAST_NAME);

-- DELETE FROM JOIN
DELETE E1 FROM EMPLOYEE1 AS E1 
JOIN EMPLOYEE1 AS E2 
WHERE E1.EMPLOYEE_ID  < E2.EMPLOYEE_ID  AND E1.FIRST_NAME = E2.FIRST_NAME;
