USE SIMPLELEARN;

/*  NORMALIZATION IS THE PROCCESS OF ELIMINATING DATA REDUNDANCY AND ENHANCE DATA INTERGRITY IN THE TABLE.
  IT ALSO HELP TO ORGAINZE THE DATA IN THE DATABASE. IT IS A MULTI STEP PROCESS THAT SETS THE DATA INTO TABULAR FORM AND REMOVE 
   THE DUPLICATED DATA FROM THE RELATIONAL TABLES 
   --> NORMAILIZATION IS DONE TO REDUCE 
   1. INSERTION, UPDATION AND DELETION ANAMOLIES 
   
   --> WHY DO WE NEED NORMAILIZATION?
   1. REMOVES DUPLICATE DATA AND DATABASE ANAOMOLISE FROM RELATIONAL TABLE 
   2. REMOVE REDUNDANCY AND COMPLEXITY OF THE DATABASE
   3. TO AVOID CREATING AND UPDATING ANY UNWANTED DATA CONNECTIONS AND DEPENDICES 
   4. TO OPTIMIZE STORAGE SPACE 
   5. ISOLATION OF DATA IS MAINTAINED 
   */