-- NUMERIC FUNCTION
/* ABSOULTE VALUE --
TO CONVERT NEGATIVE VALUE INTO POSITIVE
*/
-- ABSOULTE FUNCTION
SELECT ABS(-15); 

-- ROUND OFF FUNCTION
SELECT round(12.657, 2);

-- CELEING AND FLOOR FUNCTION
SELECT floor(12.5); -- CONVERT INTO CLOSEST/LOWSEST INTEGER
SELECT ceiling(12.5); -- CONVERT INTO CLOSEST/MAXIMUN INTEGER

-- SQUARE ROOT FUNCTION
SELECT sqrt(16);

-- POWER FUNCTION
SELECT pow(12,2);
SELECT pow(15,3); -- BASE EXPONTENT 
SELECT pow(27,1/3); -- TO EXTRACT CUBE 

-- MOD FUNCTION (RETURND REMAINDER)
SELECT MOD(12,3);
SELECT (12/3); -- TO FIND QUOTIENT

-- TRUNCATE, DEGREES,RADIAN SE DEGREE M CONVERT, GREATEST, LEAST 

COMMIT;
