USE VOLCANUS;

SELECT*FROM ORDERS;
SELECT*FROM CUSTOMER;


-- Retrieve the item names and amounts for orders placed by customers from the 'USA.'
SELECT ITEM, AMOUNT FROM ORDERS WHERE ID IN (SELECT NAME, PRODUCT FROM CUSTOMER WHERE COUNTRY ='USA');

ALTER TABLE CUSTOMER RENAME COLUMN ID TO CUSTOMER_ID;
