USE OFFICE;

CREATE TABLE STUDENT (
STD_ID INT PRIMARY KEY,
STD_NAME VARCHAR(50),
C_ID INT,
PHONE_NUM VARCHAR(10),
EMAIL VARCHAR(200)
);

CREATE TABLE COURSE (
C_ID INT PRIMARY KEY,
C_NAME VARCHAR(50),
FEE int
);
DROP TABLE COURSE;

INSERT INTO STUDENT VALUES (101, 'MOHAN', 1, 38423773, '@MOHAN.YADAV222'),
                            (102, 'SOHAN', 2, 37823773, '@SOHAN.JADHAV434'),
                            ( 103, 'ROHAN', 3, 38429873, '@ROHAN.KUMAR344'),
                            ( 104, 'MOHANI', 4, 38425673, '@MOHANI.DAVE'),
                            ( 105, 'SUHANI', 5, 36723773, '@SUHANI.SHARMA'),
                            ( 106, 'RUHANI', 6, 38428773, '@RUHANI.VERAMA'),
                            ( 107, 'KAJAL', 7, 3673773, '@KAJAL.TIWARI'),
                            ( 108, 'PUJA', 8, 38566773, '@PUJA.YADAV');
                            
INSERT INTO COURSE VALUES (1,'DA', 50000),
						  (2, 'MERN', 90000),
                           (3, 'DS', 60000),
                            (4, 'MBA', 70000),
                             (5, 'CS', 80000),
                              (6, 'FULL_STACK', 50000),
                               (7, 'FRONT END', 40000),
                                (8, 'MERN', 70000),
                                 (9, 'DA', 90000),
                                  (10, 'DS', 90000);
SELECT*FROM STUDENT;

-- LEFT JOIN

-- ANTI JOIN/ EXCULSIVE JOIN(LEFT)
SELECT*FROM STUDENT 
LEFT JOIN COURSE 
ON STUDENT.C_ID = COURSE.C_ID
WHERE COURSE.C_ID IS NULL ;    

-- -- ANTI JOIN/ EXCULSIVE JOIN(RIGHT) -- GIVES DIFFRENT VALUES FROM THE RIGHT TABLE 
SELECT*FROM STUDENT 
RIGHT JOIN COURSE 
ON STUDENT.C_ID = COURSE.C_ID
WHERE COURSE.C_ID IS NULL ;    

-- SELF JOIN 
SELECT*FROM COURSE C1
JOIN COURSE C2
ON C1.C_ID = C2.C_ID;

SELECT E1.FIRST_NAME AS EMPNAME, E2.FIRST_NAME AS MANAGER 
FROM EMPLOYEE E1
JOIN EMPLOYEE E2
ON E1.EMPLOYEE_ID = E2.MANAGER_ID;  

-- CROSS JOIN 

CREATE TABLE BANK (
CUSTMOER_ID INT PRIMARY KEY, 
CUSTMOER_NAME VARCHAR(20),
ACCOUNT_ID INT,
ACCOUNT_TYPE VARCHAR(30)
);
INSERT INTO BANK VALUES (101,'ROHAN', 103, 'SAVING'),
(102,'SOHAN', 102, 'BUSSINESS'),
(103,'MOHAN', 101, 'JOINT'),
(104,'ROHANI', 106, 'TRUST'),
(105,'MOHANI', 105, 'STUDENT'),
(106,'SUHANI', 104, 'BROKERAGE');

SELECT * FROM BANK;
SELECT B1.CUSTMOER_NAME, B2.ACCOUNT_TYPE
FROM BANK B1
JOIN BANK B2
ON B1.CUSTMOER_ID = B2.ACCOUNT_ID;

CREATE TABLE SOCIALMEDIA (
USERNAME VARCHAR(40),
follower_id INT,
followed_id INT,
FOLLOW_TIMESTAMP TIMESTAMP
);
INSERT INTO SOCIALMEDIA (USERNAME, follower_id, followed_id, FOLLOW_TIMESTAMP) VALUES
('Rahul', 1, 2, NOW()),
('Priya', 2, 1, NOW()),
('Amit', 3, 1, NOW()),
('Sneha', 1, 4, NOW()),
('Rajesh', 4, 1, NOW());
SELECT*FROM SOCIALMEDIA;

SELECT F1.USERNAME AS FOLLOWER_NAME, F2.USERNAME AS FOLLOWED_USERNAME
FROM SOCIALMEDIA F1
JOIN SOCIALMEDIA F2
ON F1.follower_id= F2.followed_id;

COMMIT;
                                                                                     