USE SIMPLELEARN;

-- WHAT IS KEYS IN SQL?
/* SQL KEY IS AN ATTRIBUTE OR SET OF ATTRIBUTES WHICH HELPS YOU TO IDENTIFY A ROW IN A TABLE
UNIQULY IDENTIFIES A ROW IN A TABLE BY COMBINATION OF ONE OR MORE COLUMNS IN A DATABASE TABLE
IT CREATES CONSTRAINT THAT CAN BE USED TO ENFORCE DATA INTERGITY IN THE TABLE 

-- WHY WE USE KEYS IN SQL
KEYS IDINTIFIES EACH RECORD UNIQUELY AND SEPERATELY
ALLOW USER TO ESTABLISH AND IDENTIFY A RELATION BETWEEN TABLE
ACCESS OR MANAGES THE STORED DATA QUICKLY AND SMOOTHLY

-- TYPES OF KEYS  

PRIMARY KEY 
( IT IDINTIFES EACH ROW UNIQUELY AND NOT NULL, 
PRIMARY KEY CAN NOT BE NULL 
IT CAN NOT HAVE DUPLICATE VALUE 
A TABLE CANNOT HAVE MORE THAN ONE PK
IT IS GIVEN TO THE USER NOT TAKEN )

CANDIDATE KEY
( IT IS A SET OF ONE OR MORE COLUMNS THAT CAN IDENTIFY A RECORD/TUPLE UNIQUELY A TABLE,
CK SHOULD NOT HAVE REDUNDANT ATTRIBUTES,
IT CAN CONTAIN NULL VALUES,
A TABLE CAN HAVE ONE OR MORE CK AND IS CALLED A MINIMAL SUPER KEY
 )
 
 ALTERNATE KEY 
 ( AK IS A SUBSET OF CK THAT CAN ALSO BE UNIQELY IDENTIFY TUPLE IN THE TABLE WHICH ARE NOT CHOOSEN AS PK)
 
 SUPER KEY 
 ( SK IS A COMBINATION OF ALL POSIBLE ATTRIBUTES WHICH CAN UNIQUELY IDENTIFY THE ROWS IN A TABLE
 IT IS A SUPERSET OF PK, CK AND AK,
 SK MAY HAVE ADDITIONAL ATTRIBUTES THAT ARE NOT NEEDED FOR UNIQUELY IDENTIFCATION,
 SK WITH LEAST NUMBERS OF ATTRIBUTES FORM THE CK)
 
 FOREGIN KEY 
 (FK IS A SET OF ATTRIBUTES IN A TABLE THAT REFERS TO THE PRIMARY KEY OF ANOTHER TABLE,
 TABLE WITH THE FK IS KNOWN AS A CHILD TABLE AND TABLE WITH PK IS KNOWN AS REFRENCED OR PARENT TABLE,
 A TABLE CAN HAVE ONE OR MORE FK AND CAN CONATIN DUPLICATE AND AS WELL AS NULL VALLUE )
 
 UNIQUE KEY 
 (IT IS SIMILAR TO PK WITH THE DIIFRENCE THAT IT CAN HAVE NULL VALUES AND 
 REDUCES COLUMN LEVEL DUPLICAY AND PK REDUCES ROW LEVEL DUPLICAICY)
 
 COMPOSITE KEY
 ( A CK IS A COMBINATION OF TWO OR MORE ATTRIBUTES THAT TOGETHER CAN UNIQUELY IDENTIFY A TUPLE IN A TABLE )

*/


/* WHAT IS GROUP BY? 
IT IS USED TO GROUP TOGETHER ANY ROWS OF A COLUMN WITH THE SAME values STORED IN THEM BASED ON A FUNCTION SPECIFIED IN THE STATEMENT
IT USES SPLIT-APPLY-COMBINE TECHINQUE FOR EXAMPLE A TABLE  HAS (a- ( A- 2, A-2), b(B-3,B-2), c(C-5,C-2) = A(4),B(5),C(7)) 
BY APPLYING SUM AGGREGATE FUNCTION)


WHAT IS ORDER BY?
IT SORTS THE RECORDS OF A COLUMN IN A table USING ASCENDING AND DESCINDING KEYWORDS IN ARRANGING ASC AND DESC ORDERS
IT ALWYAS COME AFTER GROUP BY.


WHAT IS THE DIFFRENCE BETWEEN BOTH?
 GROUP BY IS USED TO GROUP THE ROWS THAT HAVE THE SAME values
 ORDER BY IS USED TO ARRANGE THE DATA IN ASC AND DSC ORDER
 
GROUP BY ALWAYS USED BEFORE ORDER BY
 ORDER BY ALWAYS USED AFTER GROUP BY
 
 ATTRIBUT UNDER AGGREGATE FUNCTION CAN NOT BE IN GROUP BY CLAUSE 
  ATTRIBUT UNDER AGGREGATE FUNCTION CAN  BE IN ORDER BY CLAUSE 
  
  MANADTORY TO USE ANY AGGREGATE FUNCTION IN GROUP BY CLAUSE 
    AGGREGATE FUNCTION IS NOT COMPULSARY TO USE IN ORDER BY CLAUSE 
    
    GROUP BY CONTROLS THE PRSENTATION OF ROWS/TUPLES
   ORDER BY CONTROLS THE PRESTATION OF COLUMNS /FIELDS 

*/
COMMIT;

