USE UNIVERSITY; 


CREATE TABLE Students (
    student_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    date_of_birth DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Courses (
    course_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    instructor VARCHAR(100),
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Enrollments (
    enrollment_id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT,
    course_id INT,
    enrollment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES Students(student_id),
    FOREIGN KEY (course_id) REFERENCES Courses(course_id)
);


INSERT INTO Students (first_name, last_name, email, date_of_birth)
VALUES 
    ('AKSHITA', 'TIWARI', 'AKSHITA.TIWARI1970@GMAIL.COM', '2000-03-12'),
    ('AKSHAT', 'DAVE', 'AKSHat.DAVE1970@GMAIL.COM', '1998-03-09'),
    ('SONAM', 'PATEL', 'SONAM.PATEL1980@GMAIL.COM', '1999-02-02'),
    ('POORNIMA', 'TIWARI', 'POORNIMA.TIWARI@GMAIL.COM', '2000-04-04'),
    ('AAYUSH', 'SOLANKI', 'AAYUSH.SOLANKI2070@GMAIL.COM', '1999-07-08'),
    ('SANSKRITI', 'SOLANKI', 'SANSKIRITI.SOLANKI1970@GMAIL.COM', '2004-03-05'),
    ('SHAILY', 'JAISWAL', 'SHAILY.JAISWAL1970@GMAIL.COM', '1998-07-03'),
    ('ISHIKA', 'SHARMA', 'ISHIKA.SHARMA1970@GMAIL.COM', '2000-09-09'),
    ('MUSKAN', 'CHAUREY', 'MUSKAN.CHOREY1770@GMAIL.COM', '2001-03-08'),
    ('PARUL', 'PAL', 'PARUL.PAL1870@GMAIL.COM', '2003-03-09');
    
INSERT INTO Courses (title, description, instructor, start_date, end_date)
VALUES 
    ('Introduction to Programming', 'Learn basic programming concepts', 'AKSHAT DAVE', '2024-03-01', '2024-04-30'),
    ('Data Science ', 'Introduction to data science techniques', 'AKSHITA TIWARI', '2024-02-15', '2024-04-15'),
     ('Web Development program', 'Learn basic web developing concepts', 'POORNIMA TIWARI', '2024-02-15', '2024-04-15'),
      ('Full Stack ', 'Learn front-end, back-end techniques', 'SONAMPATEL', '2024-01-15', '2024-08-15'),
       ('Data Analtics ', 'Introduction to data analytics techniques', 'SANSKIRITI SOLANKI', '2024-01-10', '2024-04-15'),
        ('C Programming', 'Introduction to C programming techniques', 'AAYUSH SOLANKI', '2023-05-10', '2024-05-10'),
         ('C++ Programming ', 'Introduction to C++ programming techniques', 'ISHIKA SHARMA', '2024-02-15', '2025-04-15'),
          ('Python', 'Introduction to Python programming techniques', 'SHAILY JAISWAL', '2022-02-15', '2024-03-12'),
           (' SQL developer', 'Introduction to SQL development techniques', 'MUSKAN CHOREY', '2022-01-15', '2024-03-15'),
            ('JAVA Programming', 'Introduction to java programming techniques', 'PARUL PAL', '2024-01-09', '2025-03-06');


INSERT INTO Enrollments (student_id, course_id)
VALUES
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
    (6, 6),
    (7, 7),
    (8, 8),
	(9, 9),
	(10, 10);
    
    
-- LEFT JOIN USING STUDENT AND COURSE TABLE 
SELECT*FROM STUDENTS;
SELECT*FROM COURSES;
SELECT*FROM ENROLLMENTS;
    
SELECT S.STUDENT_ID, S.FIRST_NAME, S.LAST_NAME, C.COURSE_ID, C.TITLE, C.INSTRUCTOR 
FROM STUDENTS S
LEFT JOIN ENROLLMENTS E ON S.STUDENT_ID = E.STUDENT_ID
LEFT JOIN COURSES C ON E.COURSE_ID = C.COURSE_ID; 

-- LEFT JOIN USING STUDENT AND ENROLLMENT TABLE 
SELECT DISTINCT S.STUDENT_ID, S.FIRST_NAME, S.LAST_NAME, E.ENROLLMENT_DATE
FROM STUDENTS S 
LEFT JOIN ENROLLMENTS E
ON S.STUDENT_ID =  S.STUDENT_ID ;

-- RIGHT JOIN USING STUDENT AND COURSE TABLE 
SELECT*FROM STUDENTS;
SELECT*FROM COURSES;
SELECT*FROM ENROLLMENTS;
    
SELECT S.STUDENT_ID, S.FIRST_NAME, S.LAST_NAME, C.COURSE_ID, C.TITLE, C.INSTRUCTOR 
FROM STUDENTS S
RIGHT JOIN ENROLLMENTS E ON S.STUDENT_ID = E.STUDENT_ID
RIGHT JOIN COURSES C ON E.COURSE_ID = C.COURSE_ID; 


-- RIGHT JOIN USING STUDENT AND ENROLLMENT TABLE 
SELECT DISTINCT S.STUDENT_ID, S.FIRST_NAME, S.LAST_NAME, E.ENROLLMENT_DATE
FROM STUDENTS S 
RIGHT JOIN ENROLLMENTS E
ON S.STUDENT_ID =  S.STUDENT_ID ;


-- INNER JOIN USING STUDENT AND COURSE TABLE 
SELECT*FROM STUDENTS;
SELECT*FROM COURSES;
SELECT*FROM ENROLLMENTS;
    
SELECT S.STUDENT_ID, S.FIRST_NAME, S.LAST_NAME, C.COURSE_ID, C.TITLE, C.INSTRUCTOR 
FROM STUDENTS S
INNER JOIN ENROLLMENTS E ON S.STUDENT_ID = E.STUDENT_ID
INNER JOIN COURSES C ON E.COURSE_ID = C.COURSE_ID; 

-- INNER JOIN USING STUDENT AND ENROLLMENT TABLE 
SELECT DISTINCT S.STUDENT_ID, S.FIRST_NAME, S.LAST_NAME,E.ENROLLMENT_ID, E.ENROLLMENT_DATE
FROM STUDENTS S 
INNER JOIN ENROLLMENTS E
ON S.STUDENT_ID =  S.STUDENT_ID;

-- SELF JOIN  ON STUDENT TABLE 
SELECT*FROM STUDENTS;
SELECT DISTINCT S1.STUDENT_ID, S1.first_name, S2.first_name AS friend_name
FROM Students S1
JOIN Students S2 ON S1.STUDENT_ID <> S2.STUDENT_ID;

-- CROSS JOIN
SELECT S.student_id, S.first_name, C.course_id, C.title
FROM Students S
CROSS JOIN Courses C;   

-- DATETIME FUNCTIONS 
SELECT*FROM STUDENTS;
SELECT*FROM COURSES;
SELECT*FROM ENROLLMENTS;

SELECT 
    DATE(ENROLLMENT_DATE)
FROM
    ENROLLMENTS;
SELECT 
    TIME(ENROLLMENT_DATE)
FROM
    ENROLLMENTS;
SELECT 
    YEAR(ENROLLMENT_DATE)
FROM
    ENROLLMENTS;
SELECT 
    MONTH(START_DATE) AS MONTH
FROM
    COURSES;
SELECT 
    DAY(ENROLLMENT_DATE)
FROM
    ENROLLMENTS;
SELECT 
    MONTHNAME(START_DATE) AS MONTH_NAME
FROM
    COURSES;
SELECT 
    LAST_DAY(START_DATE) AS LAST_DAY
FROM
    COURSES;
SELECT 
    WEEK(START_DATE) AS WEEK_NAME
FROM
    COURSES;
SELECT 
    DAYNAME(START_DATE) AS DAYNAME_NAME
FROM
    COURSES;
SELECT 
    WEEKDAY(START_DATE) AS WEEK_DAY
FROM
    COURSES;
	SELECT 
    TIMESTAMPDIFF(DAY, START_DATE, END_DATE)
FROM
    COURSES;
SELECT 
    TIMESTAMPDIFF(WEEK,
        START_DATE,
        END_DATE)
FROM
    COURSES;
	SELECT 
    TIMESTAMPDIFF(HOUR,
        START_DATE,
        END_DATE)
FROM
    COURSES;
	SELECT 
    TIMESTAMPDIFF(MINUTE,
        START_DATE,
        END_DATE)
FROM
    COURSES;
SELECT 
    TIMESTAMPDIFF(SECOND,
        START_DATE,
        END_DATE)
FROM
    COURSES;


-- STRING FUNCTIONS  
SELECT 
    CONCAT(FIRST_NAME, '-', LAST_NAME)
FROM
    STUDENTS;
SELECT 
    LENGTH(FIRST_NAME)
FROM
    STUDENTS;
SELECT 
    UPPER(EMAIL)
FROM
    STUDENTS;
SELECT 
    LOWER(EMAIL)
FROM
    STUDENTS;
SELECT 
    REVERSE(FIRST_NAME) AS REVERSED_NAME
FROM
    STUDENTS;
SELECT 
    SUBSTRING(FIRST_NAME, 2, 6)
FROM
    STUDENTS;
SELECT 
    LEFT(FIRST_NAME, 3)
FROM
    STUDENTS;
SELECT 
    RIGHT(FIRST_NAME, 3)
FROM
    STUDENTS; 


-- NUMERIC FUNCTION 
SELECT*FROM STUDENTS;
SELECT*FROM COURSES;
SELECT*FROM ENROLLMENTS;


-- WINDOW FUNCTION 
SELECT STUDENT_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, row_number() OVER (ORDER BY DATE_OF_BIRTH) FROM STUDENTS;
SELECT TITLE, row_number() OVER (ORDER BY START_DATE) AS ROW_NUM FROM COURSES ;

  -- ASSIGNING UNIQUE NUMBER TO EACH ROW AND ROW NUMBER IS PROVIDED  UNIQUE NUMBER TO EACH ROW 
SELECT STUDENT_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, row_number() OVER (ORDER BY DATE_OF_BIRTH) FROM STUDENTS ;

SELECT TITLE, row_number() OVER (ORDER BY START_DATE) AS ROW_NUM FROM COURSES ;

-- RANK () 
SELECT STUDENT_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, RANK() OVER (ORDER BY DATE_OF_BIRTH) AS RANK_NUM FROM STUDENTS ;

-- DENSE RANK()
SELECT  STUDENT_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, DENSE_RANK() OVER (ORDER BY DATE_OF_BIRTH) AS DENSE_RANK_NUM FROM STUDENTS;
SELECT  STUDENT_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, row_number() OVER (ORDER BY DATE_OF_BIRTH) AS ROW_NUM FROM STUDENTS ;


 /* Question 5: 
Based on the existing tables (students, courses, and enrollments), add the following additional 
columns to each table: */

-- For Students Table: 

ALTER TABLE STUDENTS ADD COLUMN ADDRESS VARCHAR(255);
ALTER TABLE STUDENTS ADD COLUMN  phone_number VARCHAR(20);
ALTER TABLE STUDENTS ADD COLUMN GENDER ENUM('Male', 'Female', 'Other');
ALTER TABLE STUDENTS ADD COLUMN nationality VARCHAR(50); 
ALTER TABLE STUDENTS ADD COLUMN  guardian_name VARCHAR(100);







