USE SIMPLELEARN;

/* WHAT IS FUNCTION IN SQL ?
A FUNCTION IN SQL IS A SET OF SQL STATEMENT THAT PERFORM A SPECIFIC TASK,
IF YOU HAVE TO WRITE A SAME STATMENT REPEATEDLY THAT U CAN SIMPLY CREATE 
A FUNCTION HENCE INSTEAD OF WRIRTING A WHOLE QUERY U CAN SIMPLY CALL THAT FUNCTION 
TO GET THE DESIRED RESULT. IT IS DEVELOPED BY EITHER USER OR ALREADY PROVIDED BY SQL SYSTEM

SYNTAX OF FUNCTION --

DELIMITER $$ 
CREATE FUNCTION FUNCTION_NAME (
PARAMETER1, DATATYPE
PARAMETER2, DATATYPE )

RETURNS DATATYPE 
DETERMINISTIC
BEGIN
-- ENTER THE CODE FOR FUNCTION 
END $$ 
*/

-- USER DEFINED FUNCTION

DELIMITER $$ 
CREATE FUNCTION BONUSSTATUS (
SALARY CHAR(20)
)
RETURNS VARCHAR(20)
DETERMINISTIC 
BEGIN 
IF SALARY > 35000 THEN
RETURN ('ELIGBLE FOR BONUS');
ELSE 
RETURN ('NOT ELGIBLE');
END IF;
END $$
DELIMITER $$ 

SELECT BONUSSTATUS(20000);
SELECT BONUSSTATUS(80000);

-- HOW TO CALL A FUNCTON INTO ALREADY EXISTING FUNNCTION
SELECT EMPID, EMPNAME, SALARY, BONUSSTATUS(SALARY) FROM EMPLOYEE;

/* WHAT IS CAST AND CONVERT FUNCTION?

WHAT IS CAST FUNCTION?
(THE SQL CAST FUNCTION IS USED TO CONVERT COLUMN VALUES IN A TABLE OR 
ANY EXPERSSION FORM ONE DATA TYPE TO ANOTHER DATA TYPE )
IT IS USEFUL TO CONACANTAING RESULTS FROM VARIOUS DATATTYPE 
THE CAHNGES ARE DONE AS TEMPORARY BASIS AND PERMANENT DATA TYPE ARE NOT CONVERTED

SYNTAX -
CAST (EXPERSSION AS DATATYPE (LENGTH) FOR EXAMPLE SELECT CAST(76. 87 AS INT); OUTPUT 76

WHAT IS CONVERT FUNCTION?
(THE CONVERT() FUNCTION IS ALSO USED FOR CONVERTING A VALUE FROM ONE DATATYPE TO 
DIFFRENT DATATYPE WITH ONLY DIFRENCE IS SYNTAX )

SYNTAX - CONVERT (EXPERSSION, DATATYPE)
 FOR EXAMPLE ( 2022.06.07 ) AS DATE OUTPUT - 2022-06-07
  */
  
  -- CAST()customer FUNCTION
  SELECT CAST(45.68 AS SIGNED); -- INT IS NOT SUPPORTED IN MYSQL
  SELECT CAST('22,12,24' AS DATETIME);
  
  -- CAST() IT ALSO CHANGED DATATYPE OF THE COLUMN VALUES IN THE TABLE
  SELECT PRODUCTNAME, PRICE, CAST(PRICE AS SIGNED) AS NEWPRICE FROM ORDERS;
  
  -- CONVERT FUNCTION()
  SELECT CONVERT(21.345, DECIMAL(7,2));
  SELECT  CONVERT("11.10.25",DATETIME);
  SELECT CONVERT(22, YEAR);
  SELECT CONVERT('091726', TIME);



COMMIT;