USE SIMPLELEARN;

-- WHAT IS TABLE? 
/* A TABLE IS A COLLECTION OF DATA WHICH IS ORGANISED IN ROWS AND COLUMNS, A TABLE CAN BE ANY NUMBER OF ROWS BUT COLUMN WOULD BE SPECIFED 
1. HORIZONTAL VALUES ARE CALLED ROWS/TUPLES EACH ROW REPERENTS UNIQUE RECORD.
2. VERTICAL VALUES ARE CALLED ATTRIBUTES/COLUMS EACH COLUMN REPRESTENS UNIQUE FEILD.
 */

-- HOW TO CREATE TABLE? 
CREATE TABLE IF NOT EXISTS EMPLOYEES(
ID INT PRIMARY KEY,
NAME VARCHAR(80),
AGE INT,
CITY VARCHAR(80),
SALARY DECIMAL (8,2)
);

-- DROP TABLE (IT DELETES THE DEFINATION AND OVERALL STRUCTURE OF THE TABLE PERMANATLY)
DROP TABLE EMPLOYEES;
DESC EMPLOYEES;

-- INSERT TABLE (IT INSERT NEW RECORDS EITHER SINGLE OR MULTIPLE)

INSERT INTO EMPLOYEES (ID, NAME,AGE, CITY, SALARY) 
VALUES (1, 'RAM', 23, 'INDORE', 25000.45);
SELECT*FROM EMPLOYEES;

-- DELETE TABLE (IT REMOVES ALL THE ROWS FROM THE TABLE OR WITH WHERE CONDITION SPECIFC ROW CAN BE DELTED)
DELETE FROM EMPLOYEES WHERE ID =1;

-- TRUNCATE TABLE (IT DELETES THE ALL THE RECORDS FROM THE TABLE, ROLLBACK IS NOT POSSIBLE SO DATA WOULD BE PERMANANTELY DELTED)
TRUNCATE TABLE EMPLOYEES;
SELECT*FROM EMPLOYEES;

-- ALTER TABLE (ADD, MODIFY AND DELETE COLUMNS OF AN EXISTING TABLE)

ALTER TABLE EMPLOYEES ADD COLUMN DOB DATE AFTER AGE;
SELECT*FROM EMPLOYEES;

-- RENAME TABLE (TO RENAME TABLE)
ALTER TABLE EMPLOYEES RENAME TO EMPLOYEESS;

-- COPY TABLE (COPY THE FROM AN EXISITNG TABLE INTO ANOTHER SQL STATEMENT)
CREATE TABLE EMPDETAILS SELECT*FROM EMPLOYEE;
SELECT*FROM EMPDETAILS;

COMMIT;