-- TO CREATE DATBASE
CREATE DATABASE IF NOT exists PROJECT;

-- TO SEE THE ALL THE DATABASE IN THE SCHEMA 
SHOW DATABASES;

-- HOW TO SELECT DATABASE
USE PROJECT;

-- TO DELETE THE DATABASE PERMANATELY
DROP DATABASE PROJECT;

COMMIT;