USE SIMPLELEARN;
-- WHAT IS SQL JOINS? 
/*  COMBINES ROWS FROM MORE THAN ONE TABLE BY USING COMMON COLUMNS IN BOTH TABLES

FOR EXAMPLE-- TABLE A AND B HAVE COLUMNS/ROWS = TABLE_1 [COLUMNS(A,B,C) ROWS(1,2,3)] AND TABLE_2 [COLUMNS( C, D, E) AND ROWS(4,5)]
= JOINED TABLE [COLUMN (A,B,C,D,E) ROWS (1,2,3,4,5)] 
OR 
TABLE_1 COLUMNS(A,B,C) AND TABLE_2 COLUMNS( C, D, E) = JOINED TABLE COLUMN (A,B,C,D,E)

---> USES OF SQL JOIN
1. FLEXIBILTY (IT ALLOWS USER TO ACCESS AND MANAGE RECORDS FROM MORE THAN ONE TABLE EASILY
2. DATA REDUNDANCY (ALLOWS UP TO KEEP  DATA REDUNDANCY AT LOWEST SO THAN WE CAN DECREASE THE DATA ANOMAILES )
3. EFFECIENCY ( ALLOWS US TO SHOW THE RESULT QUICKLY THAn any other sub QUERIES)

----> TYPES OF SQL JOINS 
1. INNER JOIN
(INNER JOIN RETURNS A NEW TABLE BY COMBINING RECORD THAT ONLY HAVE MATCHING VALUES IN BOTH THE TABLE, 
JOINED BASED ON COMMON COLUMN,
COMPARES ROWS OF TABLE 1 TO ROWS OF TABLE 2, RETURNS SELECTED AND MATCHED RECORDS

FOR EXAMPLE - LEFT TABLE RECORD = (1,2,3,4) RIGHT TABLE RECORD (3,4,5,6) = INNER JOINT RECORD (3,4)

SYNTAX-  TABLE1.COLUMN1, TABLE1.COLUMN2 
TABLE2.COLUMN 2 
FROM TABLE1
INNER JOIN TABLE2
ON TABLE1.COLUMN= TABLE2.COLUMN)

 2. OUTER JOIN
 ( OUTER JOIN RETURNS ALL THOSE RECORDS WHICH ARE EITHER IN THE LEFT TABLE OR RIGHT TABLE, 
 RETURNS ALL THE RECORDS EVEN IF THEY DO NOT MATCH EACH OTHER,
 FOR EXAMPLE -  A TABLE RECORD = (1,2,3,4) B TABLE RECORD = (3,4,5,6)= OUTER JOINED TABLE RECORD(1,2,3,4,5,6)
 
 SYNTAX- SELECT TABLE1.COULMN1, TABLE1.COLUMN2, TABLE2.COUMN1, TABLE2.COLUMN2
 FROM TABLE1
 FULL OUTER JOIN TABLE2
 ON TABLE1.COLUMN = TABLE2.COLUMN;   
 
 3. LEFT JOIN 
 ( LEFT JOIN RETURNS ALL THE ROWS FROM THE LEFT TABLE AND MATCHING ROWS FROM THE RIGHT TABLE,)
 FOR EXAMPLE =  LEFT TABLE RECORD = (1,2,3,4) RIGHT TABLE RECORD = (3,4,5,6)= LEFT JOINED TABLE RECORD(1,2,3,4)
 
 SYNTAX - SELECT COULMN_LIST 
 FROM TABLE1
 LEFT JOIN TABLE2
 ON TABLE1.COLUMN = TABLE2.COLUMN;
 
 4. RIGHT JOIN 
 ( LEFT JOIN RETURNS ALL THE ROWS FROM THE RIGHT TABLE AND ALL MATCHING RECORDS FROM THE LEFT TABLE)
 FOR EXAMPLE =  LEFT TABLE RECORD = (1,2,3,4) RIGHT TABLE RECORD = (3,4,5,6)= LEFT JOINED TABLE RECORD(3,4,5,6)
 
 SYNTAX - SELECT COULMN_LIST 
 FROM TABLE1
 RIGHT JOIN TABLE2
 ON TABLE1.COLUMN = TABLE2.COLUMN;
 
 
 5. CROSS JOIN
  */
  
  COMMIT;