SHOW databases;
CREATE DATABASE UNIVERSITY1;
USE UNIVERSITY1; 
CREATE TABLE STUDENT (
ROLL_NO INT PRIMARY KEY auto_increment,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
CITY VARCHAR (100), 
MARKS DECIMAL(5,2) 
);

INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, CITY, MARKS)
VALUES ('RAM', 'RAGHUWANSHI', 'AYODHYA', 90.23),
('SHYAM', 'YADAV', 'BANARAS', 80.23),
('ROHAN', 'PATEL', 'MUMBAI', 70.23),
('MOHAN', 'PATIL', 'BHOPAL', 60.23),
('SOHAN', 'YADAV', 'DHAR', 60.23),
('PRIYA', 'JADHAV', 'JABLPUR', 60.23),
('SUPRIYA', 'SHRIVASTATV', 'KASHMIR', 80.23),
('RAMCHARAN', 'PRAJAPAT', 'HYDERABAD', 40.23),
('KALU', 'SHARMA', 'PUNE', 60.23),
('DHOLU', 'DWEVDI', 'KHANDHWA', 50.23);

SELECT*FROM STUDENT;

-- SELECT QUERIES 
SELECT FIRST_NAME,CITY FROM STUDENT;
SELECT COUNT(FIRST_NAME) AS NUMBER_OF_STUDENTS FROM STUDENT;
SELECT MAX(MARKS) AS MAXIMUM_MARKS FROM STUDENT;
SELECT MIN(MARKS) AS MINIIMUM_MARKS FROM STUDENT;
SELECT SUM(MARKS) AS SUM_OF_MARKS FROM STUDENT;
SELECT avg(MARKS) AS AVEARGE_OF_MARKS FROM STUDENT;

-- CLAUSES (CONDITIONS)
SELECT*FROM STUDENT  WHERE MARKS >= 85;
SELECT*FROM STUDENT  WHERE MARKS <= 85;
SELECT*FROM STUDENT  WHERE MARKS < 85;
SELECT*FROM STUDENT  WHERE MARKS > 85;
SELECT*FROM STUDENT  WHERE MARKS = 90.23;
SELECT*FROM STUDENT  WHERE MARKS BETWEEN 70 AND 80;
SELECT*FROM STUDENT  WHERE MARKS >= 70 AND MARKS <= 80;
SELECT*FROM STUDENT ORDER BY MARKS;
SELECT*FROM STUDENT ORDER BY MARKS DESC;
SELECT*FROM STUDENT ORDER BY MARKS DESC LIMIT 1;
SELECT*FROM STUDENT  WHERE MARKS = (SELECT MAX(MARKS)FROM STUDENT);
SELECT*FROM STUDENT  WHERE MARKS =  MAX(MARKS); -- INVALID USE OF GROUP FUNCTION

 -- GROUP BY/ HAVING 
 SELECT CITY, COUNT(FIRST_NAME) AS NO_OF_STUDENTS FROM STUDENT GROUP BY CITY ORDER BY CITY;
  SELECT CITY, COUNT(FIRST_NAME) AS NO_OF_STUDENTS FROM STUDENT GROUP BY CITY HAVING NO_OF_STUDENTS> 1 ORDER BY CITY;
  
  -- STRING FUNCTIONS 
  SELECT CONCAT('RAM',' - ', 'RAGHUWANSHI');
  SELECT CONCAT(FIRST_NAME, '- ',LAST_NAME) FROM STUDENT;
  SELECT length('RAM');  -- LENGTH CHECKING 
  SELECT UPPER('small');   -- UPPER FUNCTION
  SELECT LOWER('BIG'); -- LOWER FUNCTION
 SELECT reverse('RAM');  -- REVERSE FUNCTION
 SELECT substring('ANITA SHARMA',7, 6); -- SUBSTRING FUNCTION
 SELECT LEFT('ANITA SHRMA', 3); -- LEFT FUNCTION
  SELECT RIGHT('ANITA SHRMA', 3); -- RIGHT FUNCTION
 SELECT TRIM('      ANITA SHRAMA     '); -- TRIM(REMOVE SPACES, LEADING AND TRAILING)
   SELECT LTRIM('      ANITA SHRAMA     '); -- REMOVE LEFT SPACES 
    SELECT RTRIM('      ANITA SHRAMA     '); -- REMOVE RIGHT SPACES
    SELECT replace('ANITA SHARMA', 'SHARMA', 'VERMA'); 
    SELECT LOCATE('SHARMA','ANITA SHRAMA'  ); -- TO FIND POSITIONS 
    SELECT concat_ws('-', 'red', 'green', 'yellow', 'pink'); -- to put delimater 
    
    -- DATETIME FUNCTION
  SELECT now(); -- CURRENT DATE AND TIME 
  SELECT CURDATE(); -- RETUEN CURRENT DATE
  SELECT curtime(); -- RETUEN CURRENT TIME
  SELECT DATE('2024-02-27 01:24:37'); -- EXTRACT DATE 
  SELECT TIME('2024-02-27 01:24:37');  -- EXTRACT TIME
    SELECT YEAR('2024-02-27 01:24:37'); -- EXTRACT YEAR
      SELECT MONTH('2024-02-27 01:24:37'); -- EXTRACT MONTH
        SELECT DAY('2024-02-27 01:24:37'); -- EXTRACT DAY
        SELECT MONTHNAME( '2024-02-27 01:24:37'); -- EXTRACT MONTH NAME
          SELECT LAST_DAY('2024-02-27'); -- EXTRACT LAST DAY
          SELECT WEEK('2024-02-27'); -- EXTRACT WEEK
          SELECT dayname('2024-02-27'); 
           SELECT WEEKDAY('2024-02-27');
		SELECT DAYNAME('2024-02-27');
        SELECT HOUR('2024-02-27');
    SELECT HOUR(NOW());
     
    
-- CROSS JOIN 

CREATE TABLE MEALS (
MEALID INT PRIMARY KEY, 
MEALNAME VARCHAR(10),
PRICE INT
);

CREATE TABLE DRINKS (
DRINKID INT PRIMARY KEY,
DRINKNAME VARCHAR(20),
PRICE INT
);
INSERT INTO MEALS VALUES (1, 'OMLET', 50),
                          (2,'FRIED EGG',70),
                          (3, 'SAUSAGE', 80);
                          
	INSERT INTO DRINKS VALUES (1, 'ORANGE JUICE', 10),
                               (2, 'TEA', 5),
                               (3, 'COFFEE', 10);
SELECT M.MEALNAME, M.PRICE AS MEAL_PRICE, D.DRINKNAME, D.PRICE AS DRINK_PRICE
FROM MEALS M
CROSS JOIN DRINKS D;

CREATE TABLE STUDENT (
SID INT PRIMARY KEY auto_increment ,
S_NAME VARCHAR(20),
TEACHERID_ INT 
);
SELECT*FROM STUDENT;
DROP TABLE STUDENT;

INSERT INTO STUDENT (SID, S_NAME, TEACHERID) VALUES ( 1, 'ROHAN', 2),
( 'SOHAN', 3),
( 'MOHAN', 4),
( 'ROHANI', 1),
( 'MOHANI', 5); 

   


COMMIT;
